---
# 多账号选择登录
loginSelect:
  - key: uuid
    type: string
    rules:
      - required: true
        message: 缺少登录识别码
        code: 1000
  - key: result
    type: string
    rules:
      - required: true
        message: 缺少登录识别码
        code: 1000